# Generated by Django 4.0.4 on 2022-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('H', 'Health'), ('F', 'Food'), ('D', 'Drinks'), ('M', 'Misc')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.ManyToManyField(to='main_app.amenity'),
        ),
    ]
