# Generated by Django 4.0.3 on 2022-05-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_comment_content_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.venue'),
        ),
    ]
