# Generated by Django 4.0.3 on 2022-05-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Venue',
            new_name='venue',
        ),
    ]
