# Generated by Django 4.0.4 on 2022-05-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
