# Generated by Django 4.0.4 on 2022-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.DateField(verbose_name='When did you go?'),
        ),
    ]
